[libraries]

fpga_cores.files = [
  'src/*.vhd',
]

exp_golomb.files = [
  'src/exponential_golomb/*.vhd',
]

str_format.files = [
  'dependencies/hdl_string_format/src/*.vhd',
]

fpga_cores_sim.files = [
  'sim/*.vhd',
]

tb.files = [
  'testbench/*.vhd',
]

osvvm.files = [
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/AlertLogPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/CoveragePkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/MemoryPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/MessageListPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/MessagePkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/NamePkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/NameStorePkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/OsvvmContext.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/OsvvmGlobalPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/RandomBasePkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/RandomPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/RandomProcedurePkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/ReportPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/ResizePkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/ResolutionPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/ScoreboardGenericPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_slv.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/ScoreboardPkg_int.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/SortListPkg_int.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/TbUtilPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/TextUtilPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/TranscriptPkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/osvvm/VendorCovApiPkg.vhd',
]

vunit_lib.files = [
  'env/lib/python3.14/site-packages/vunit/vhdl/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/core/src/core_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/core/src/stop_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/string_ops/src/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/logging/src/ansi_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/logging/src/file_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/logging/src/location_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/logging/src/log_deprecated_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/logging/src/logger_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/logging/src/log_handler_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/logging/src/log_levels_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/logging/src/print_pkg.vhd',

  'env/lib/python3.14/site-packages/vunit/vhdl/path/src/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/dictionary/src/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/api/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/codec-2008p.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/codec_builder-2008p.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/codec_builder.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/codec.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/data_types_context.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/data_types_private_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/dict_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/event_common_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/event_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/event_private_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/id_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/integer_array_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/queue_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/queue_pool_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/string_ptr_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/data_types/src/types.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/array/src/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/random/src/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/run/src/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/check/src/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/com/src/*.vhd',
  'env/lib/python3.14/site-packages/vunit/vhdl/verification_components/src/*.vhd',
]

JSON.files = [
  'env/lib/python3.14/site-packages/vunit/vhdl/JSON-for-VHDL/src/*.vhdl',
]

