include ../opt/msim-options.mk

LIB = common_lib
ROOT_DIR ?= .
SOURCE_LIST += common_pkg.vhd
SOURCE_LIST += sr_delay.vhd
SOURCE_LIST += synchronizer.vhd
SOURCE_LIST += edge_detector.vhd
SOURCE_LIST += pulse_sync.vhd

include ../opt/msim-rules.mk


