include ../opt/msim-options.mk

LIB = osvvm_lib
VHDL_VERSION := -2008
ROOT_DIR ?= .
SOURCE_LIST := RandomBasePkg.vhd
SOURCE_LIST += SortListPkg_int.vhd
SOURCE_LIST += RandomPkg.vhd
SOURCE_LIST += NamePkg.vhd
SOURCE_LIST += MessagePkg.vhd
SOURCE_LIST += CoveragePkg.vhd

include ../opt/msim-rules.mk


